### ISSUE TITLE
Move code from 2014 site into this repo

### ISSUE THREAD

**Issue by edrushka** [mozilla/2015.mozillafestival.org#11]
@mmmavis can you please update this repo with last year's code? Thank you!

**Comment by mmmavis** [comment]
To-Dos
- [ ] push w/e is in the [2014 theme repo](https://github.com/mozilla/2014.mozillafestival.org) to this repo
- [ ] make sure [staging](http://mozfest.mofostaging.net/) links to this repo
- [ ] make sure [prod](http://mozillafestival.org/) links to this repo

**Comment by mmmavis** [comment]
Hey @jdotpz 
Could you check for me and see if ec2-50-19-172-65.compute-1.amazonaws.com (prod) and ec2-54-163-74-27.compute-1.amazonaws.com(staging) are still alive? I seem to have trouble ssh'ing to the production server.
I just need to change the git remote config so they point to this repo instead of https://github.com/mozilla/2014.mozillafestival.org.git.  But if we are going to have another server for this year's MozFest site I guess we can just leave it as is.

**Comment by ScottDowne** [comment]
Pretty sure this repo is all 2015 now, so we can probably close this.
