### ISSUE TITLE
Clarify session terminology, modes

### ISSUE THREAD

**Issue by ryanw-se** [mozilla/2015.mozillafestival.org#156]
When looking at the required questions to submit a proposal, one of the questions is "What is the mode of your session?". This is very unclear and almost everyone I ask has no clue what it means. This should be simplified using more typical terminology.

**Comment by ryanpitts** [comment]
+1

As our team discussed outreach for MozFest session proposals, we ran into the same thing. "Mode" seemed very confusing, on initial read for sure, but also in using the dropdown options to categorize many types of sessions. One example we thought of was a session talking about [using satellite data to track declining coastlines](http://projects.propublica.org/louisiana/), which could fall under Learning, Science, or Journalism.

"Theme" also felt a little strange, after writing up a few pieces of narrative to then have to step back and figure out which single word describes your session.

**Comment by thornet** [comment]
Hey, huge thanks for the feedback. The current form represents some earlier thinking about the program. 

We're in the process of updating our messaging, including on the themes and session terminology. 

What do you all think of the following edits?

#### 1. Add two new questions: 
* "This year, Mozfest is focusing strongly on leadership development, advocacy and impact. How would your session interpret and respond to those elements?"
* "Who are your target participants, and what are their needs, interests and motivations for joining your session?"
#### 2. Update THEME [select multiple]: 
* Privacy and the web
* Ethics of the web
* Web literacy
* Economy of the web
* Inclusion and the web
* Environment and the web
* Future web now
* Place and the web

#### 3. Remove "Audience" and "Mode."

cc @Saallen @edrushka @ScottDowne

**Comment by edrushka** [comment]
I agree with removing audience and mode. New themes look fine to me (I assume they encompass the proposed sessions so far).

**Comment by Saallen** [comment]
I made a suggestion and wonder what folks here think about it. Which is to remove audience and mode but keep themes as is but add new themes as a context paragraph at the top of the Call page. I am afraid by adding these new themes as drop down selectors people will identify as tracks. However I am understanding @ryanpitts  point about selecting single word to describe session. Eager to know what @KevZawacki  and @edrushka  think

**Comment by ryanpitts** [comment]
@Saallen I think that sounds great, is there an example page somewhere to help visualize what you're describing?

**Comment by KevZawacki** [comment]
+1, I think simpler the form is, the more applications you'll see. "Mode" is confusing me, too.

**Comment by thornet** [comment]
Thanks for the feedback! Sounds like we're proposing: 

#### 0. Add an explanatory text at the top of the page. (placeholder language)
"This year we're exploring a range of topics. We welcome sessions that engage with those areas on inquiry: 
* Privacy and the web
* Ethics of the web
* Web literacy
* Economy of the web
* Inclusion and the web
* Environment and the web
* Future web now
* Place and the web

#### 1. Add two new questions: 
* "This year, Mozfest is focusing strongly on leadership development, advocacy and impact, as well as the exploratory topics listed above. How would your session interpret and respond to these themes?"
* "Who are your target participants, and what are their needs, interests and motivations for joining your session?"

#### 2. Remove "Audience", "Mode" and "Theme"

**Comment by thornet** [comment]
Thanks for the feedback! Sounds like we're proposing: 

#### 0. Add an explanatory text at the top of the page. (placeholder language)
"This year we're exploring a range of topics. We welcome sessions that engage with those areas on inquiry: 
* Privacy and the web
* Ethics of the web
* Web literacy
* Economy of the web
* Inclusion and the web
* Environment and the web
* Future web now
* Place and the web

#### 1. Add two new questions: 
* "This year, Mozfest is focusing strongly on leadership development, advocacy and impact, as well as the exploratory topics listed above. How would your session interpret and respond to these themes?"
* "Who are your target participants, and what are their needs, interests and motivations for joining your session?"

#### 2. Remove "Audience", "Mode" and "Theme"

**Comment by edrushka** [comment]
I have a couple questions:
- will there still be a way to identify the different styles of session (e.g. fireside chat, hackjam, discussion, etc.)?
- Do the topics = tracks?
- Is the list of topics a drop-down where people can check more than one? There's already a lot of text at the top, so I don't feel confident people will read this if we don't make it part of the submission process.
- What does 'Place and the web' mean? Is this a phrase most people will understand?

**Comment by ScottDowne** [comment]
Previously proposed sessions are still going to have a mode item, not much we can do about that. We just need to keep this in mind while reviewing older sessions.

Consider as an alternative to removing them, just make it optional, and add an empty line to the dropdown. and it starts with the empty line selected. So if people don't know what it's about, or it doesn't apply to them, they can ignore it.

Maybe have an "all" item for audience instead of an empty one.

**Comment by Saallen** [comment]
@thornet Plus one to the new questions. I think the second question allows facilitators to choose the topics they relate to.

@edrushka - we are not asking people to identify styles of sessions- as far as I remember we cut this from last year. Themes are the new word de jour- tracks in previous years have been too narrow so we are expanding the topics to encompass more themes under each. Which is why I wanted the topics in the top introduction text rather than the drop down menu. I am hoping Michelles proposed second question will highligh these new topics and allow submissions take them into account.
 Yes- I think people should be able to pick more than one topic. 
Place and web- can be expanded as city or location and the web, in this case we are located in London but we would like to see how other folks identify "place' here.

@ScottDowne - good shout out about old modes-  Maybe lets keep them. What do other folks feel here?

I am eager to make these changes asap- can I have access to the google form or a copy to start adding these changes then we can make amendments on the form pushed to the website??

**Comment by SpikeUK** [comment]
Agree to people being able to 'tag' their proposed session with more than one 'topic' - maybe gives the facility to create 'tag clouds'?
I did not understand 'mode' either but worked-out that it was shorthand for 'mode of delivery' - so presentation, fireside chat, workshop were the main options.

**Comment by erikao** [comment]
just wanna add a "yayyyyy" and THANK YOU for these updates.

**Comment by Saallen** [comment]
:fireworks:

**Comment by Saallen** [comment]
We have made a simplier edit as seen on #161  so closing this issue.
