### ISSUE TITLE
MozFest 2015 site: Revise and clean up UX wireframes

### ISSUE THREAD

**Issue by edrushka** [mozilla/2015.mozillafestival.org#16]
Meta Ticket in /plan: https://github.com/MozillaFoundation/plan/issues/374

Driver: @edrushka
MoFo Designer: @iamjessklein 
Contract UI Designer: tbd

### To Do: Prep Roberto's files' to hand off to UI contractor.
* Creative brief: https://studiomofo.etherpad.mozilla.org/mozfest-site-creative-brief
* Notes from handoff meeting with Roberto: https://etherpad.mozilla.org/mozfesthandoff
* Roberto's sitemap: https://www.dropbox.com/s/j2ksnqbu205er18/MozFext%20website%20structure%20proposal%20.pdf?dl=0
* Roberto's wireframes: https://projects.invisionapp.com/share/AY2GUNPXU#/screens
* Roberto's final files: https://drive.google.com/a/mozilla.com/folderview?id=0B4q3TCz6z_aJY2ZHQ3ZRV1BLTDg&usp=sharing

**Comment by iamjessklein** [comment]
After talking with Sarah Allen, I learned that there are a few different "states" or "phases" to the site release. 

* Phase 1 - May 2015(ish) - Request for Proposals stage: the calls to action are 1) submit a session and 2) sign up to attend as either a volunteer or attendee
* Phase 2 - TBD - Schedule is up! - the calls to action are 1) look at schedule 2) sign up to attend as either a volunteer or attendee ( possibly a 3rd for submitting a proposal for things like fireside chats or ignite talk - like events
* Phase 3 - TBD - MozFest Live: the calls to action are 1) find a session to attend 2) sign up to attend as volunteer or attendee 3) participate remotely 4) participate on social media 
* Phase 4 - TBD -Post MozFest: the calls to action are 1) submit posts, github repos, tweets for documentation 2) Read the recap 3) Stay in touch with your community that you met during the Festival.

Sarah - can you take a look and let me know if I got that right ?

With this in mind, I took a stab at updating the sitemap and working on the homepage and proposal form. I was deeply inspired by the tagline "come with an idea, leave with a community" and so that concept is integrated into the designs. 

Please look at and provide feedback on redpen for the [sitemap](https://redpen.io/qvfdc550aa619e8ff8), the [homepage](https://redpen.io/rkcca5efd7025ff09b) and the [form](https://redpen.io/ue7e57793eaa53f431). @edrushka I am flagging the need for content here, as I put in a bunch of placeholder copy and images. 

![sitemap-v2](https://cloud.githubusercontent.com/assets/535012/7252594/900c4bd6-e804-11e4-8341-d59377eabf9f.png)

**Comment by Saallen** [comment]
Hey @iamjessklein This all looks great- I have one comment on the different phases.
P2- schedule is up and CTA is around register for ticket or as a volunteer but submit Fringe events- so events which will take place the week preceding the festival. Call for Proposals will be closed, and sucessful sessions chosen,  if the schedule is live. :+1:

**Comment by edrushka** [comment]
@Saallen can you clarify if you want the proposals to be visible to the public once they've been submitted?

**Comment by Saallen** [comment]
Yes please, people who submitt sessions are always keen to see their submissions on the website- Plus it opens the community to collaboration.

**Comment by edrushka** [comment]
A further note: there's no need for the submissions to have a 'like' button, as sessions aren't chosen by vote. A share button could be cool, but that's a nice to have, not MVP.

**Comment by iamjessklein** [comment]
Ok so - are there any additional requirements for these submissions? Will they need to be searchable? Filterable? etc

**Comment by edrushka** [comment]
AFAIK, no. MVP is just viewable. Sarah might have some other nice-to-haves.

**Comment by iamjessklein** [comment]
So, are you thinking something like [the sessions page on srccon](http://srccon.org/sessions/proposals/)?

Follow up: Are proposals editable by participants or is it a one shot go?

**Comment by edrushka** [comment]
I anticipate we'll get 500+ session proposals, so a single scrolling page like SRCCON will be unmanageable. If we go a similar route, we'll need some kind of sorting mechanism (maybe tags?) What are your thoughts here?

**Comment by iamjessklein** [comment]
My first thought would be to get the MVP site up without the proposals showing.
My second thought is to that the proposals should incorporate tags and be searchable - sorting by date submitted. 
-----
I still have the larger question of will users have the ability to go back in and edit their proposals? If so, this site is going to need an infrastructure to support that - and a login.

**Comment by Saallen** [comment]
Hey- 
It would be great that sessions were under titles/tracks/themes so then they can be filtered this way.
If we use a scheduling app that allowed sessions to be submitted to this app then  it would be nice that facilitators would have option to change their proposal until a certain date. if this functionaility is not available then its not the end of the world

**Comment by iamjessklein** [comment]
Here's the last wireframe [on redpen](https://redpen.io/onf9ef6f2f7d1ce729)for the MozFest landing - live. 

![mozfest-live](https://cloud.githubusercontent.com/assets/535012/7543143/47114924-f590-11e4-84a3-74f9d7f64ff1.png)
