### ISSUE TITLE
Participation guidelines - how we work in the Open

### ISSUE THREAD

**Issue by Saallen** [mozilla/2015.mozillafestival.org#217]
Post call with Chris R and Melissa C we want to continue to encourage people to stay working in the open post festival. So we decided to add one line to the participation guidelines page.
For example
- we are working in the open, join us mlz.com/
- we are working in the Open, see how we do this mlz

@OpenMatt do you have any suggestions for pages which highlights how we work in the Open? Do we want this it be a Mozilla wide page or a MoFo link? @hannahkane

**Comment by hannahkane** [comment]
I'm a little confused by this. Are we creating a new page, or linking to something that exists?

**Comment by Saallen** [comment]
Hi @hannahkane not a new page but adding one line to the exisiting participation guidelines page. 
The link is to another page which already exists and highlights how we are working in the open
Sarah

**Comment by hannahkane** [comment]
What is the url for the page we are linking to that already exists?

**Comment by SpikeUK** [comment]
@hannahkane I believe we are talking about https://2015.mozillafestival.org/guidelines
Hope this helps

**Comment by hannahkane** [comment]
Thanks, @SpikeUK. I understood the Guidelines page to be the page we're linking *from*, but what is the page we're linking *to*?

**Comment by OpenMatt** [comment]
@Saallen I have this, which I will be adding to: 
* http://blog.workopen.org 

But that's it. Should have much more to point at through 2016.

**Comment by Saallen** [comment]
Thanks @OpenMatt I would be very happy to link through to this. @Melechuga could this be the website that would keep the open spirit alive post Mozfest?

**Comment by hannahkane** [comment]
What about this then? (changes totally welcome):

* Add a section after the "Raising Issues" section; same white background
* Headline (same style as R-E-S-P-E-C-T): Working in the Open
* Copy: MozFest planning is done in the open [perhaps link to the "Submission Process" page] because working in the open is one of our core values. We hope participants will benefit from this culture of transparency and collaboration during the Festival, and will take the open ethos back to their work and projects after MozFest. We recommend bookmarking WorkOpen.org and reading through the interviews with passionate advocates for open practices.

**Comment by Saallen** [comment]
I like this :+1: 
Can we add the continue to work in the open......
As we want them to keep the work they started at mozfest in the open post festival.
"and will continue to work with the open ethos in their projects after Mozfest"..

**Comment by hannahkane** [comment]
Sounds good. I'll close this and file a separate implementation ticket.

**Comment by hannahkane** [comment]
New ticket: https://github.com/mozilla/2015.mozillafestival.org/issues/253
