### ISSUE TITLE
Benchmarking for tote bag, tshirt, stickers, name tag

### ISSUE THREAD

**Issue by cassiemc** [mozilla/2015.mozillafestival.org#228]
I think we can push the design for the tote bag ( #225 ), stickers ( #209 ) and tshirt ( #208 ) beyond a simple mozfest logo, if there's time. I'm interesting in seeing some benchmarks of other contemporary designs to see if that triggers any new ideas (a pinterest board collection would be handy).

This should feel like a cohesive set of designs with the festival guide ( #212 ) and Name Tag ( #210 ).

Assigning this to @natalieworth for a first task. Feel free to start looking into this but we can also go over this tomorrow before you begin.  

cc @Saallen @hannahkane @adiladil

**Comment by cassiemc** [comment]
Can't yet assign @natalieworth, but will do once she joins the github group.

**Comment by SpikeUK** [comment]
:+1:

**Comment by cassiemc** [comment]
@SpikeUK the Festival Guide is slightly different, more information-dense, but yes – it should definitely feel like a cohesive set. I do like the idea of including the name tag, will adjust the issue title.

Note: We'll need to print the totes and t-shirts in one-color for budget reasons.

**Comment by SpikeUK** [comment]
^^ Thank you @cassiemc - accept that we have cost constraints for t-shirts and tote bags though

**Comment by natalieworth** [comment]
@adiladil @cassiemc 
1. I've created a Pinterest board https://www.pinterest.com/nataliejworth/mozfest-2015-benchmarks/ focused on more contemporary festival and illustration branding. In particular, I feel that we could explore iconography, isometric designs, or something more abstract. It could be neat to possibly include illustrations representing the manifesto or things that Mozilla (and Mozillians) are involved with (e.g. badges, add-ons, contributors, etc.) through this style:
https://www.pinterest.com/pin/345088390176008532/

2. Or even something more typographic:
https://www.pinterest.com/pin/345088390176008285/

3. I also feel like isometric illustrations are popular in graphically representing communities/ areas, deconstructions of events or organizational components, etc. so that may also be something to explore in terms of the style: 
https://www.pinterest.com/pin/345088390176009391/
https://www.pinterest.com/pin/345088390176008369/

4. Or alternatively, there is also the possibility of creating something more abstract, but still representative of Mozilla/ the web/ community/ interconnections:
https://www.pinterest.com/pin/345088390176008978/

**Comment by cassiemc** [comment]
This is fantastic! Have always loved that Matt Stevens example and the food ones too. I think we should use the space icons from #213 to save time, but your benchmarks raise the idea that we can connect them with lines or other sorts of abstract shapes. cc @adiladil

**Comment by cassiemc** [comment]
I think we can close this one.

Let's go with inspiration from this: https://www.pinterest.com/pin/345088390176008532/ using the Space icons. Isometric and more complex illustration (though freakin' awesome) will be hard to pull off in the amount of time we have. We might be able to experiment with some lines and drawings between the icons to connect them, if there's time. cc @adiladil
