### ISSUE TITLE
Add a disclaimer for Sched

### ISSUE THREAD

**Issue by edrushka** [mozilla/2015.mozillafestival.org#99]
Background: Email addresses submitted via the Submit a Proposal form will be publicly viewable in a database. We'd like to give people an option if they are not ok with this.

I suggest:

Information submitted via this form will be publicly viewable in a database. Please contact festival@mozilla.org if you prefer to submit your session without using this form.

@KevZawacki is this clear and friendly?
cc @ScottDowne @Saallen @simonwex

**Comment by KevZawacki** [comment]
Perfect!

**Comment by Saallen** [comment]
Tweek- from Legal - we must say we are ultimately creating an account here. Legal will email language as they feel we need more here
Security worries about creating passwords- are we creating a password for them to join as an account?

**Comment by Saallen** [comment]
Suggested by legal @KevZawacki @edrushka @ScottDowne 

"When you submit information via this form, Mozilla will create an account for you on sched.com [LINK] and the information will be publicly viewable in a database. By submitting your session proposal, you are agreeing to your information being handled according to Mozilla's privacy policy [LINK] and you are also agreeing to sched.com's terms of service [LINK] and privacy policy [LINK]. Please be aware that this will opt you in to future communications from Sched. Please contact festival@mozilla.org if you prefer to submit your session without using this form."


Side comment:
Sarah, I've assumed that Mozilla is also getting a copy of the submitted information. If that's not the case, the second sentence should say instead: "By submitting your session proposal, you are agreeing to sched.com's terms of service [LINK] and privacy policy [LINK]."

**Comment by ScottDowne** [comment]
We are getting a copy of the submission in terms of it's also living in google docs which we have access to, and we have access to the data in sched. It's never living on a mozilla server though.

We don't actually create an account with sched for anyone. We just need their email so if we accept their proposal we have a way to contact them, and a way to invite them to sched.

My instinct is telling me this is not worth it. That's a huge wall of text to give to a user just so we have a bit of convenience managing the proposals. The decision to use sched was made mostly because Mozilla was already using it. That didn't save us from this nonsense.

I still consider not using sched to be an option. We're already storing proposals in a google doc, and we already have a table for a schedule setup (https://mozillafestival-org-2015.herokuapp.com/expect), which wouldn't be hard to use to make a schedule. We have what we need to launch without sched.

**Comment by Saallen** [comment]
@ScottDowne I am with you on this thought. I left the  MoCo security meeting on Friday feeling very doubtful about moving forward with this app but decided if I was still unsure by Monday morning I was going to email you. I felt then as I feel now that we are going to use a product that goes against all our privacy and user ethos as a company. Ti,to feels right- sched.com does'nt.
We dont need a schedule application just yet- we do need a way for the Space Wranglers to view the submissions in a clear and more managable way but the first time the group will examine them is at a MozFest retreat in Scotland in 3 weeks. 
I know we have been working in this for about 6 weeks but my gut feelings is not to use this application.I am proposing we dont use sched.com and I will go back to reseaching other options.
What do others think?

**Comment by ScottDowne** [comment]
I think the main reason I have doubts is because there isn't enough of a benefit.

Even without the privacy and security concerns, I'm concerned with how we're using it. What they do, display a schedule. What we want, something the space wranglers can use to view and manage 300+ proposals. I'm not convinced it's much better than a google doc for viewing and managing proposals. I also don't think they ever considered this a helpful feature.

We should consider a separate thing that just manages this kind of data, which would free us up on picking a scheduling app for what it does best, schedules.

**Comment by ScottDowne** [comment]
We decided to no longer use Sched for proposal management.

Can still use for schedule display once we have a list of accepted sessions, because a simple schedule doesn't require email or password usage.
